name: Run Markdown Refiner

on:
  workflow_dispatch:  # Allows you to manually trigger this from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai pymupdf python-dotenv GitPython requests

      - name: Run the script
        run: |
          python md_auto_refine.py
